use crate::token::{Token, TokenKind};

#[derive(Debug, Clone)]
pub struct Snippet {
    pub keyword: &'static str,
    pub label: &'static str,
    pub insert_text: &'static str,
    pub description: &'static str,
    pub context_hint: &'static str, // "expr", "decl", "any"
}

pub static SNIPPETS: &[Snippet] = &[
    Snippet { keyword: "funcion", label: "funcion — definir función",
        insert_text: "funcion ${1:nombre}(${2:param})${3: -> Tipo} {\n\t${0}\n}",
        description: "Define una función con parámetros y tipo de retorno opcional",
        context_hint: "decl" },
    Snippet { keyword: "variable", label: "variable — declarar variable mutable",
        insert_text: "variable ${1:nombre}${2:: Tipo} = ${0:valor}",
        description: "Declara una variable mutable con tipo opcional",
        context_hint: "decl" },
    Snippet { keyword: "constante", label: "constante — declarar constante",
        insert_text: "constante ${1:NOMBRE}${2:: Tipo} = ${0:valor}",
        description: "Declara una constante inmutable",
        context_hint: "decl" },
    Snippet { keyword: "si", label: "si — condicional",
        insert_text: "si (${1:condicion}) {\n\t${0}\n}${2: sino {\n\t\n}}",
        description: "Condicional si/sino",
        context_hint: "expr" },
    Snippet { keyword: "mientras", label: "mientras — bucle",
        insert_text: "mientras (${1:condicion}) {\n\t${0}\n}",
        description: "Bucle mientras",
        context_hint: "expr" },
    Snippet { keyword: "para", label: "para — bucle for estilo C",
        insert_text: "para (${1:variable i = 0}; ${2:condicion}; ${3:incremento}) {\n\t${0}\n}",
        description: "Bucle for con inicialización, condición e incremento",
        context_hint: "expr" },
    Snippet { keyword: "repetir", label: "repetir — bucle por cantidad",
        insert_text: "repetir (${1:cantidad}) {\n\t${0}\n}",
        description: "Bucle que se repite N veces",
        context_hint: "expr" },
    Snippet { keyword: "clase", label: "clase — definir clase",
        insert_text: "clase ${1:Nombre} {\n\t${2:campos}\n\n\t${0}\n}",
        description: "Define una clase",
        context_hint: "decl" },
    Snippet { keyword: "tipo", label: "tipo — definir tipo algebraico (enum)",
        insert_text: "tipo ${1:Nombre} = ${2:Variante1}${3: | Variante2}",
        description: "Define un tipo algebraico/enum",
        context_hint: "decl" },
    Snippet { keyword: "funcion main", label: "funcion main — punto de entrada",
        insert_text: "funcion main() {\n\t${0}\n}",
        description: "Función principal del programa",
        context_hint: "decl" },
    Snippet { keyword: "importar", label: "importar — importar módulo",
        insert_text: "importar \"std/${0}\"",
        description: "Importa un módulo de la stdlib",
        context_hint: "decl" },
    Snippet { keyword: "coincidir", label: "coincidir — pattern matching",
        insert_text: "coincidir (${1:expr}) {\n\tcaso ${2:patron} -> {\n\t\t${0}\n\t}\n}",
        description: "Pattern matching con casos",
        context_hint: "expr" },
    Snippet { keyword: "rasgo", label: "rasgo — definir interfaz",
        insert_text: "rasgo ${1:Nombre} {\n\tfuncion ${2:metodo}(${3:param})${4: -> Tipo}\n}",
        description: "Define un rasgo (interfaz/trait)",
        context_hint: "decl" },
    Snippet { keyword: "implementa", label: "implementa — implementar rasgo",
        insert_text: "implementa ${1:Rasgo} para ${2:Clase} {\n\t${0}\n}",
        description: "Implementa un rasgo para una clase",
        context_hint: "decl" },
    Snippet { keyword: "hilo", label: "hilo — lanzar hilo",
        insert_text: "hilo {\n\t${0}\n}",
        description: "Lanza un hilo ligero",
        context_hint: "expr" },
    Snippet { keyword: "requiere", label: "requiere — precondición",
        insert_text: "requiere ${1:condicion}${2:, \"${3:mensaje}\"}",
        description: "Precondición para Design by Contract",
        context_hint: "decl" },
    Snippet { keyword: "asegura", label: "asegura — postcondición",
        insert_text: "asegura ${1:resultado} ${2:condicion}",
        description: "Postcondición para Design by Contract",
        context_hint: "decl" },
];
